platform :ios, '9.0'

source 'https://github.com/AbdullahAsendar/react-native-private-repo'
source 'https://github.com/CocoaPods/Specs.git'

target 'MySdk-native' do
  use_frameworks!

  pod 'React'
  pod 'React-Core'
  pod 'ReactCommon'
  pod 'React-CoreModules'
  pod 'FBLazyVector'
  pod 'FBReactNativeSpec'
  pod 'RCTRequired'
  pod 'RCTTypeSafety'
  
  pod 'RNFastImage', :git=> 'https://github.com/DylanVann/react-native-fast-image.git', :tag=> 'v8.3.3'

  pod 'FBSDKCoreKit', '5.8.0'
  pod 'FBSDKLoginKit', '5.8.0'
  pod 'FBSDKShareKit', '5.8.0'
  pod 'FBAudienceNetwork', '6.9.0'

  pod 'RCTTypeSafety'
end
